name: Assign when issue or PR opened

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      # CLI also workds with PR
      - run: gh issue edit $ISSUE --add-assignee $CREATOR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
          CREATOR: ${{ github.event.issue.user.login }}
