name: Move To Next Iteration

on:
  workflow_dispatch:
  schedule:
    # Runs "at 05:00, only on Sunday" (see https://crontab.guru)
    - cron: '0 5 * * 0'

jobs:
  move-to-next-iteration:
    name: Move to next iteration
    runs-on: ubuntu-latest

    steps:
    - uses: blombard/move-to-next-iteration@master
      with:
        owner: celestiaorg
        number: 27
        token: ${{ secrets.ADD_TO_PROJECT_PAT }}
        iteration-field: "Weekly-Sprint - 2024 -"
        iteration: current
        new-iteration: next
        excluded-statuses: "Done"
