# Deactivated as this is solved with GitHub Projects workflow
name: Automation on issue and PR creation

on: {}
  # issues:
  #   types:
  #     - opened
  # pull_request:
  #   types:
  #     - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.1
        with:
          project-url: https://github.com/orgs/celestiaorg/projects/27
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
